<?php    if(!defined('IN_UCHOME')) { exit('Access Denied'); } class dbstuff { var $querynum = 0; var $link; var $rZJ6glaFc; var $charset_wap; function connect($dbhost, $dbuser, $dbpw, $dbname = '', $pconnect = 0, $halt = TRUE) { if($pconnect) { if(!$this->link = @mysql_pconnect($dbhost, $dbuser, $dbpw)) { $halt && $this->halt('Can not connect to MySQL server'); } } else { if(!$this->link = @mysql_connect($dbhost, $dbuser, $dbpw, 1)) { $halt && $this->halt('Can not connect to MySQL server'); } } if($this->version() > '4.1') { if($this->rZJ6glaFc) { @mysql_query("SET character_set_connection=$this->rZJ6glaFc, character_set_results=$this->rZJ6glaFc, character_set_client=binary", $this->link); } if($this->version() > '5.0.1') { @mysql_query("SET sql_mo\x64e=''", $this->link); } } if($dbname) { @mysql_select_db($dbname, $this->link); } } function select_db($dbname) { return mysql_select_db($dbname, $this->link); } function fetch_array($query, $result_type = MYSQL_ASSOC) { return mysql_fetch_array($query, $result_type); } function query($sql, $type = '') { if($this->rZJ6glaFc != $this->charset_wap) { $sql = jTtcgMMUE($sql,$this->rZJ6glaFc,$this->charset_wap); } if(D_BUG) { global $_SGLOBAL; $sqlstarttime = $sqlendttime = 0; $mtime = explode(' ', microtime()); $sqlstarttime = number_format(($mtime[1] + $mtime[0] - $_SGLOBAL['supe_starttime']), 6) * 1000; } $func = $type == 'UNBUFFERED' && @function_exists('mysql_unbuffered_query') ? 'mysql_unbuffered_query' : 'mysql_query'; if(!($query = $func($sql, $this->link)) && $type != 'SILENT') { $this->halt('MySQL Query Error', $sql); } if(D_BUG) { $mtime = explode(' ', microtime()); $sqlendttime = number_format(($mtime[1] + $mtime[0] - $_SGLOBAL['supe_starttime']), 6) * 1000; $sqltime = round(($sqlendttime - $sqlstarttime), 3); $explain = array(); $info = mysql_info(); if($query && preg_match("/^(select )/i", $sql)) { $explain = mysql_fetch_assoc(mysql_query('EXPLAIN '.$sql, $this->link));
} $_SGLOBAL['debug_query'][] = array('sql'=>$sql, 'time'=>$sqltime, 'info'=>$info, 'explain'=>$explain); } $this->querynum++; return $query; } function affected_rows() { return mysql_affected_rows($this->link); } function error() { return (($this->link) ? mysql_error($this->link) : mysql_error()); } function errno() { return intval(($this->link) ? mysql_errno($this->link) : mysql_errno()); } function result($query, $row) { $query = @mysql_result($query, $row); return $query; } function num_rows($query) { $query = mysql_num_rows($query); return $query; } function num_fields($query) { return mysql_num_fields($query); } function free_result($query) { return mysql_free_result($query); } function insert_id() { return ($id = mysql_insert_id($this->link)) >= 0 ? $id : $this->result($this->query("\x53\105\114E\103\124 last_insert_id()"), 0); } function fetch_row($query) { $query = mysql_fetch_row($query); return $query; } function fetch_fields($query) { return mysql_fetch_field($query); } function version() { return mysql_get_server_info($this->link); } function close() { return mysql_close($this->link); } function halt($message = '', $sql = '') { $dberror = $this->error(); $dberrno = $this->errno(); $help_link = "http://faq.comsenz.c\x6f\155/?type=\155\x79sq\x6c&dberrno=".rawurlencode($dberrno)."&dberror=".rawurlencode($dberror); echo "<div style=\"position:absolute;font-size:11px;font-family:v\145r\144\x61\156\x61,a\162\x69a\x6c;background:#EBEBEB;padding:0.5em;\">
				<b>MySQL E\162\x72\157\x72</b><br>
				<b>\x4de\x73\163\x61g\145</b>: $message<br>
				<b>\x53\121\114</b>: $sql<br>
				<b>\105r\x72o\x72</b>: $dberror<br>
				<b>\x45rrn\157.</b>: $dberrno<br>
				<a href=\"$help_link\" target=\"_blank\">\103li\143\153 here to seek help.</a>
				</div>"; exit(); } } ; ?>
