<?php    if(!defined('IN_UCHOME')) { exit('Access Denied'); } $doid = empty($_GET['doid'])?0:intval($_GET['doid']); $id = empty($_GET['id'])?0:intval($_GET['id']); if(empty($_POST['refer'])) $_POST['refer'] = "space.\x70\150\x70?\144o=doing&view=me"; if(submitcheck('addsubmit')) { $add_doing = 1; if(empty($_POST['spacenote'])) { if(!checkperm('allowdoing')) { ckspacelog(); showmessage('no_privilege'); }  
ckrealname('doing');  
ckvideophoto('doing');  
cknewuser();  
if(checkperm('seccode') && !ckseccode($_POST['seccode'])) { showmessage('incorrect_code'); }  
$waittime = interval_check('post'); if($waittime > 0) { showmessage('operating_too_fast', '', 1, array($waittime)); } } else { if(!checkperm('allowdoing')) { $add_doing = 0; }  
if(!ckrealname('doing', 1)) { $add_doing = 0; }  
if(!ckvideophoto('doing', array(), 1)) { $add_doing = 0; }  
if(!cknewuser(1)) { $add_doing = 0; } $waittime = interval_check('post'); if($waittime > 0) { $add_doing = 0; } }  
$mood = 0; preg_match("/\[em\:(\d+)\:\]/s", $_POST['message'], $ms); $mood = empty($ms[1])?0:intval($ms[1]); $message = getstr($_POST['message'], 200, 1, 1, 1);  
$message = preg_replace("/\[em:(\d+):]/i\x73", "<img src=\"image/face/\\1.gif\" \143l\141s\163=\"face\">", $message); $message = preg_replace("/\<br.*?\>/is", ' ', $message); if(strlen($message) < 1) { showmessage('should_write_that'); } if($add_doing) { $setarr = array( 'uid' => $_SGLOBAL['supe_uid'], 'username' => $_SGLOBAL['supe_username'], 'dateline' => $_SGLOBAL['timestamp'], 'message' => $message, 'mood' => $mood, 'ip' => getonlineip() );  
$newdoid = inserttable('doing', $setarr, 1); }  
$setarr = array('note'=>$message); $credit = $experience = 0; if(!empty($_POST['spacenote'])) { $reward = getreward('updatemood', 0); $setarr['spacenote'] = $message; } else { $reward = getreward('doing', 0); } updatetable('spacefield', $setarr, array('uid'=>$_SGLOBAL['supe_uid'])); if($reward['credit']) { $credit = $reward['credit']; } if($reward['experience']) { $experience = $reward['experience']; } $setarr = array( 'mood' => "mood='$mood'", 'updatetime' => "updatetime='$_SGLOBAL[timestamp]'", 'credit' => "credit=credit+$credit", 'experience' => "experience=experience+$experience", 'lastpost' => "lastpost='$_SGLOBAL[timestamp]'" ); if($add_doing) { if(empty($space['doingnum'])) { 
$doingnum = getcount('doing', array('uid'=>$space['uid'])); $setarr['doingnum'] = "doingnum='$doingnum'"; } else { $setarr['doingnum'] = "doingnum=doingnum+1"; } } $_SGLOBAL['db']->query("UPDATE ".tname('space')." SET ".implode(',', $setarr)." WHERE uid='$_SGLOBAL[supe_uid]'");  
if($add_doing && ckprivacy('doing', 1)) { $feedarr = array( 'appid' => UC_APPID, 'icon' => 'doing', 'uid' => $_SGLOBAL['supe_uid'], 'username' => $_SGLOBAL['supe_username'], 'dateline' => $_SGLOBAL['timestamp'], 'title_template' => cplang('feed_doing_title'), 'title_data' => saddslashes(serialize(sstripslashes(array('message'=>$message)))), 'body_template' => '', 'body_data' => '', 'id' => $newdoid, 'idtype' => 'doid' ); $feedarr['hash_template'] = md5($feedarr['title_template']."\t".$feedarr['body_template']); 
$feedarr['hash_data'] = md5($feedarr['title_template']."\t".$feedarr['title_data']."\t".$feedarr['body_template']."\t".$feedarr['body_data']); 
inserttable('feed', $feedarr); }  
updatestat('doing'); showmessage('do_success', $_POST['refer'], 0); } elseif (submitcheck('commentsubmit')) { if(!checkperm('allowdoing')) { ckspacelog(); showmessage('no_privilege'); }  
ckrealname('doing');  
cknewuser();  
$waittime = interval_check('post'); if($waittime > 0) { showmessage('operating_too_fast', '', 1, array($waittime)); } $message = getstr($_POST['message'], 200, 1, 1, 1);  
$message = preg_replace("/\[em:(\d+):]/\151\163", "<img src=\"image/face/\\1.gif\" \143\x6c\x61\163\163=\"face\">", $message); $message = preg_replace("/\<br.*?\>/\151\163", ' ', $message); if(strlen($message) < 1) { showmessage('should_write_that'); } $updo = array(); if($id) { $query = $_SGLOBAL['db']->query("S\x45\114\x45C\x54 * \106\122\117\x4d ".tname('docomment')." WHERE id='$id'"); $updo = $_SGLOBAL['db']->fetch_array($query); } if(empty($updo) && $doid) { $query = $_SGLOBAL['db']->query("\123\105\114\x45\103T * FR\x4fM ".tname('doing')." WHERE doid='$doid'"); $updo = $_SGLOBAL['db']->fetch_array($query); } if(empty($updo)) { showmessage('docomment_error'); } else {  
if(isblacklist($updo['uid'])) { showmessage('is_blacklist'); } } $updo['id'] = intval($updo['id']); $updo['grade'] = intval($updo['grade']); $setarr = array( 'doid' => $updo['doid'], 'upid' => $updo['id'], 'uid' => $_SGLOBAL['supe_uid'], 'username' => $_SGLOBAL['supe_username'], 'dateline' => $_SGLOBAL['timestamp'], 'message' => $message, 'ip' => getonlineip(), 'grade' => $updo['grade']+1 );  
if($updo['grade'] >= 3) { $setarr['upid'] = $updo['upid']; 
} $newid = inserttable('docomment', $setarr, 1);  
$_SGLOBAL['db']->query("UPDATE ".tname('doing')." SET replynum=replynum+1 WHERE doid='$updo[doid]'");  
if($updo['uid'] != $_SGLOBAL['supe_uid']) { $note = cplang('note_doing_reply', array("space.p\150\x70?\144\157=doing&doid=$updo[doid]&highlight=$newid")); notification_add($updo['uid'], 'doing', $note);  
getreward('comment',1, 0, 'doing'.$updo['doid']); }  
updatestat('docomment'); showmessage('do_success', $_POST['refer'], 0); }  
if($_GET['op'] == 'delete') { if(submitcheck('deletesubmit')) { if($id) { $allowmanage = checkperm('managedoing'); $query = $_SGLOBAL['db']->query("\x53EL\105C\x54 dc.*, d.uid \141\x73 duid FR\x4f\115 ".tname('docomment')." dc, ".tname('doing')." d WHERE dc.id='$id' AND dc.doid=d.doid"); if($value = $_SGLOBAL['db']->fetch_array($query)) { if($allowmanage || $value['uid'] == $_SGLOBAL['supe_uid'] || $value['duid'] == $_SGLOBAL['supe_uid'] ) {  
updatetable('docomment', array('uid'=>0, 'username'=>'', 'message'=>''), array('id'=>$id)); if($value['uid'] != $_SGLOBAL['supe_uid'] && $value['duid'] != $_SGLOBAL['supe_uid']) {  
getreward('delcomment', 1, $value['uid']); } } } } else { include_once(S_ROOT.'./source/function_delete.php'); deletedoings(array($doid)); } showmessage('do_success', $_POST['refer'], 0); } } elseif ($_GET['op'] == 'getcomment') { include_once(S_ROOT.'./source/class_tree.php'); $tree = new tree(); $list = array(); $highlight = 0; $count = 0; if(empty($_GET['close'])) { $query = $_SGLOBAL['db']->query("\x53E\114\x45\x43\124 * \x46\122\117M ".tname('docomment')." WHERE doid='$doid' ORDER BY dateline"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['uid'], $value['username']); $tree->setNode($value['id'], $value['upid'], $value); $count++; if($value['authorid'] = $space['uid']) $highlight = $value['id']; } } if($count) { $values = $tree->getChilds(); foreach ($values as $key => $vid) { $one = $tree->getValue($vid); $one['layer'] = $tree->getLayer($vid) * 2; $one['style'] = "padding-\154\145\x66\x74:{$one['layer']}em;"; if($one['id'] == $highlight && $one['uid'] == $space['uid']) { $one['style'] .= 'color:red;font-weight:bold;'; } $list[] = $one; } } realname_get(); } include template('cp_doing');  ?>
