<?php    if(!defined('IN_UCHOME') || !defined('qVh0gqGnK')) { exit('Access Denied'); } $_SGLOBAL['i'] = 0; $_SGLOBAL['block_search'] = $_SGLOBAL['block_replace'] = array(); function parse_template($tpl) { global $_SGLOBAL, $_SC, $_SCONFIG;  
$_SGLOBAL['sub_tpls'] = array($tpl); $tplfile = S_ROOT.'./'.$tpl.'.htm'; $objfile = S_ROOT.'./data/tpl_cache/'.str_replace('/','_',$tpl).'.php';  
if(!file_exists($tplfile)) { $tplfile = str_replace('/'.$_SCONFIG['template'].'/', '/default/', $tplfile); } $template = sreadfile($tplfile); if(empty($template)) { exit("\124\145mp\154\x61t\x65 \146i\x6c\145 : $tplfile \116\x6ft found \157r have \156o a\x63\143\145s\x73!"); }  
$template = preg_replace("/\<\!\-\-\{template\s+([a-z0-9_\/]+)\}\-\-\>/ie", "readtemplate('\\1')", $template);  
$template = preg_replace("/\<\!\-\-\{template\s+([a-z0-9_\/]+)\}\-\-\>/ie", "readtemplate('\\1')", $template);  
$template = preg_replace("/\<\!\-\-\{block\/(.+?)\}\-\-\>/ie", "blocktags('\\1')", $template);  
$template = preg_replace("/\<\!\-\-\{\x61\x64\/(.+?)\}\-\-\>/ie", "adtags('\\1')", $template);  
$template = preg_replace("/\<\!\-\-\{da\164\x65\((.+?)\)\}\-\-\>/ie", "datetags('\\1')", $template);  
$template = preg_replace("/\<\!\-\-\{avatar\((.+?)\)\}\-\-\>/ie", "avatartags('\\1')", $template);  
$template = preg_replace("/\<\!\-\-\{\x65v\x61\154\s+(.+?)\s*\}\-\-\>/ies", "evaltags('\\1')", $template);  
 
$var_regexp = "((\\\$[a-zA-Z_\x7f-\xff][a-zA-Z\060-9_\x7f-\xff]*)(\[[a-zA-\132\060-9_\-\.\"\'\[\]\$\x7f-\xff]+\])*)"; $template = preg_replace("/\<\!\-\-\{(.+?)\}\-\-\>/s", "{\\1}", $template); $template = preg_replace("/([\n\r]+)\t+/s", "\\1", $template); $template = preg_replace("/(\\\$[a-zA-Z\060-9_\[\]\'\"\$\x7f-\xff]+)\.([a-zA-Z_\x7f-\xff][a-zA-\x5a\060-9_\x7f-\xff]*)/s", "\\1['\\2']", $template); $template = preg_replace("/\{(\\\$[a-zA-\x5a\x30-9_\[\]\'\"\$\.\x7f-\xff]+)\}/s", "<?=\\1?>", $template); $template = preg_replace("/$var_regexp/es", "addquote('<?=\\1?>')", $template); $template = preg_replace("/\<\?\=\<\?\=$var_regexp\?\>\?\>/es", "addquote('<?=\\1?>')", $template);  
$template = preg_replace("/\{\145\x6c\163\x65\151\x66\s+(.+?)\}/ies", "stripvtags('<?\160\x68\x70 } \x65\154seif(\\1) { ?>','')", $template); $template = preg_replace("/\{\145\154\x73e\}/\151\x73", "<?\x70\150p } \145\154se { ?>", $template);  
for($i = 0; $i < 6; $i++) { $template = preg_replace("/\{loop\s+(\S+)\s+(\S+)\}(.+?)\{\/loop\}/ies", "stripvtags('<?ph\160 if(\x69\163_a\x72\162\141\x79(\\1)) { \146\x6f\x72\145a\143h(\\1 a\x73 \\2) { ?>','\\3<?\x70\x68\x70 } } ?>')", $template); $template = preg_replace("/\{loop\s+(\S+)\s+(\S+)\s+(\S+)\}(.+?)\{\/loop\}/ies", "stripvtags('<?\160hp \151\x66(\151\x73_\141\162\162\x61\171(\\1)) { \x66\157rea\x63h(\\1 \141\163 \\2 => \\3) { ?>','\\4<?ph\160 } } ?>')", $template); $template = preg_replace("/\{\151f\s+(.+?)\}(.+?)\{\/\151\146\}/ies", "stripvtags('<?\x70\150p i\146(\\1) { ?>','\\2<?\160\150\x70 } ?>')", $template); }  
$template = preg_replace("/\{([a-zA-Z_\x7f-\xff][a-zA-\x5a\x30-9_\x7f-\xff]*)\}/s", "<?=\\1?>", $template);  
if(!empty($_SGLOBAL['block_search'])) { $template = str_replace($_SGLOBAL['block_search'], $_SGLOBAL['block_replace'], $template); }  
$template = preg_replace("/ \?\>[\n\r]*\<\? /s", " ", $template);  
$template = "<?\x70hp \x69\146(!\144\x65\x66\x69\156\x65\144('IN_UCHOME')) \x65\170it('Access Denied');?><?\x70\150p subtplcheck('".implode('|', $_SGLOBAL['sub_tpls'])."', '$_SGLOBAL[timestamp]', '$tpl');?>$template<?\x70\x68\160 ob_out();?>";  
if(!swritefile($objfile, $template)) { exit("File: $objfile \143an \x6e\157t be write!"); } } function addquote($var) { return str_replace("\\\"", "\"", preg_replace("/\[([a-zA-\132\x30-9_\-\.\x7f-\xff]+)\]/s", "['\\1']", $var)); } function striptagquotes($expr) { $expr = preg_replace("/\<\?\=(\\\$.+?)\?\>/s", "\\1", $expr); $expr = str_replace("\\\"", "\"", preg_replace("/\[\'([a-zA-\x5a\x30-9_\-\.\x7f-\xff]+)\'\]/s", "[\\1]", $expr)); return $expr; } function evaltags($php) { global $_SGLOBAL; $_SGLOBAL['i']++; $search = "<!--EVAL_TAG_{$_SGLOBAL['i']}-->"; $_SGLOBAL['block_search'][$_SGLOBAL['i']] = $search; $_SGLOBAL['block_replace'][$_SGLOBAL['i']] = "<?p\150p ".stripvtags($php)." ?>"; return $search; } function blocktags($parameter) { global $_SGLOBAL; $_SGLOBAL['i']++; $search = "<!--BLOCK_TAG_{$_SGLOBAL['i']}-->"; $_SGLOBAL['block_search'][$_SGLOBAL['i']] = $search; $_SGLOBAL['block_replace'][$_SGLOBAL['i']] = "<?ph\160 block(\"$parameter\"); ?>"; return $search; } function adtags($pagetype) { global $_SGLOBAL; $_SGLOBAL['i']++; $search = "<!--AD_TAG_{$_SGLOBAL['i']}-->"; $_SGLOBAL['block_search'][$_SGLOBAL['i']] = $search; $_SGLOBAL['block_replace'][$_SGLOBAL['i']] = "<?p\150p adshow('$pagetype'); ?>"; return $search; } function datetags($parameter) { global $_SGLOBAL; $_SGLOBAL['i']++; $search = "<!--DATE_TAG_{$_SGLOBAL['i']}-->"; $_SGLOBAL['block_search'][$_SGLOBAL['i']] = $search; $_SGLOBAL['block_replace'][$_SGLOBAL['i']] = "<?p\150\160 \145c\x68o sgmdate($parameter); ?>"; return $search; } function avatartags($parameter) { global $_SGLOBAL; $_SGLOBAL['i']++; $search = "<!--AVATAR_TAG_{$_SGLOBAL['i']}-->"; $_SGLOBAL['block_search'][$_SGLOBAL['i']] = $search; $_SGLOBAL['block_replace'][$_SGLOBAL['i']] = "<?\x70\150\160 \145\143ho avatar($parameter); ?>"; return $search; } function stripvtags($expr, $statement='') { $expr = str_replace("\\\"", "\"", preg_replace("/\<\?\=(\\\$.+?)\?\>/s", "\\1", $expr)); $statement = str_replace("\\\"", "\"", $statement); return $expr.$statement; } function readtemplate($name) { global $_SGLOBAL, $_SCONFIG; $tpl = strexists($name,'/')?$name:agF2gTdKE."/tpl/$_SCONFIG[template]/$name"; $tplfile = S_ROOT.'./'.$tpl.'.htm'; $_SGLOBAL['sub_tpls'][] = $tpl; if(!file_exists($tplfile)) { $tplfile = str_replace('/'.$_SCONFIG['template'].'/', '/default/', $tplfile); } $content = sreadfile($tplfile); return $content; } ; ?>
