<?php    if(!defined('IN_UCHOME')) { exit('Access Denied'); }  
$perpage = 5; $perpage = mob_perpage($perpage); $list = $ols = $fuids = array(); $count = 0; $page = empty($_GET['page'])?0:intval($_GET['page']); if($page<1) $page = 1; $start = ($page-1)*$perpage;  
ckstart($start, $perpage); if($_GET['view'] == 'online') { $theurl = "space.\x70\x68p?uid=$space[uid]&\144\x6f=friend&view=online"; $actives = array('me'=>' class="active"'); $wheresql = ''; if($_GET['type']=='near') { $theurl = "space.p\150p?uid=$space[uid]&d\157=friend&view=online&type=near"; $wheresql = " WHERE ma\x69\x6e.\151p='".getonlineip(1)."'"; } elseif($_GET['type']=='friend' && $space['feedfriend']) { $theurl = "space.p\150\160?uid=$space[uid]&\144o=friend&view=online&type=friend"; $wheresql = " WHERE \x6d\x61\151\x6e.uid IN ($space[feedfriend])"; } else { $_GET['type']=='all'; $theurl = "space.\160h\x70?uid=$space[uid]&\144o=friend&view=online&type=all"; $wheresql = ' WHERE 1'; } $count = $_SGLOBAL['db']->result($_SGLOBAL['db']->query("S\x45\114E\x43\124 COUNT(*) F\122O\115 ".tname('session')." m\141\x69n $wheresql"), 0); if($count) { $query = $_SGLOBAL['db']->query("\123\105\114E\103T f.resideprovince, f.residecity, f.sex, f.note, f.spacenote, \155a\151\x6e.*
			FRO\x4d ".tname('session')." \155a\151\156
			LEFT JOIN ".tname('spacefield')." f \x4f\116 f.uid=\x6dai\156.uid
			$wheresql
			ORDER BY \155a\x69\156.l\x61\x73\x74a\143t\151\x76\x69t\171 DESC
			LIMIT $start,$perpage"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { if($value['magichidden']) { $count = $count - 1; continue; } if($_GET['type']=='near') { if($value['uid'] == $space['uid']) { $count = $count-1; continue; } } realname_set($value['uid'], $value['username']); $value['p'] = rawurlencode($value['resideprovince']); $value['c'] = rawurlencode($value['residecity']); $value['isfriend'] = ($value['uid']==$space['uid'] || ($space['friends'] && in_array($value['uid'], $space['friends'])))?1:0; $ols[$value['uid']] = $value['lastactivity']; $value['note'] = getstr($value['note'], 35, 0, 0, 0, 0, -1); $list[$value['uid']] = $value; } } $multi = multi($count, $perpage, $page, $theurl); } elseif($_GET['view'] == 'visitor' || $_GET['view'] == 'trace') { $theurl = "space.\160h\160?uid=$space[uid]&d\x6f=friend&view=$_GET[view]"; $actives = array('me'=>' class="active"'); if($_GET['view'] == 'visitor') { 
$count = $_SGLOBAL['db']->result($_SGLOBAL['db']->query("S\105LECT COUNT(*) FR\x4fM ".tname('visitor')." \155ai\156 WHERE \x6d\141\151\156.uid='$space[uid]'"), 0); $query = $_SGLOBAL['db']->query("\123\x45\x4c\105\x43T f.resideprovince, f.residecity, f.note, f.spacenote, f.sex, \x6dain.vuid AS uid, \155\141\151\156.vusername AS username, ma\x69\156.dateline
			\106R\117\x4d ".tname('visitor')." ma\x69n
			LEFT JOIN ".tname('spacefield')." f O\116 f.uid=m\141i\156.vuid
			WHERE \155\141\151n.uid='$space[uid]'
			ORDER BY m\141\x69\156.dateline DESC
			LIMIT $start,$perpage"); } else { 
$count = $_SGLOBAL['db']->result($_SGLOBAL['db']->query("\123EL\105C\124 COUNT(*) \106\x52\117M ".tname('visitor')." \x6d\x61\151\156 WHERE \x6d\141\x69\x6e.vuid='$space[uid]'"), 0); $query = $_SGLOBAL['db']->query("\x53\105\x4c\x45\103\124 s.username, s.name, s.namestatus, s.groupid, f.resideprovince, f.residecity, f.note, f.spacenote, f.sex, m\141\x69\156.uid AS uid, \x6d\x61\x69\x6e.dateline
			\x46\122OM ".tname('visitor')." m\x61i\156
			LEFT JOIN ".tname('space')." s O\116 s.uid=m\x61\151\156.uid
			LEFT JOIN ".tname('spacefield')." f O\x4e f.uid=\x6d\x61i\156.uid
			WHERE \155\x61i\x6e.vuid='$space[uid]'
			ORDER BY \x6d\x61\x69\156.dateline DESC
			LIMIT $start,$perpage"); } if($count) { while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['uid'], $value['username'], $value['name'], $value['namestatus']); $value['p'] = rawurlencode($value['resideprovince']); $value['c'] = rawurlencode($value['residecity']); $value['isfriend'] = ($value['uid']==$space['uid'] || ($space['friends'] && in_array($value['uid'], $space['friends'])))?1:0; $fuids[] = $value['uid']; $value['note'] = getstr($value['note'], 28, 0, 0, 0, 0, -1); $list[$value['uid']] = $value; } } $multi = multi($count, $perpage, $page, $theurl); } elseif($_GET['view'] == 'blacklist') { $theurl = "space.\160h\x70?uid=$space[uid]&d\157=friend&view=$_GET[view]"; $actives = array('me'=>' class="active"'); $count = $_SGLOBAL['db']->result($_SGLOBAL['db']->query("SEL\105CT COUNT(*) \106\x52\x4fM ".tname('blacklist')." \155ai\x6e WHERE \x6d\141\151\156.uid='$space[uid]'"), 0); if($count) { $query = $_SGLOBAL['db']->query("\x53\105\x4c\x45\103\x54 s.username, s.name, s.namestatus, s.groupid, \x6d\x61i\156.dateline, \155ai\156.buid AS uid
			\106\122\117M ".tname('blacklist')." \x6da\x69\156
			LEFT JOIN ".tname('space')." s \117N s.uid=\155\141i\156.buid
			WHERE \155\141i\156.uid='$space[uid]'
			ORDER BY \155\x61\151\x6e.dateline DESC
			LIMIT $start,$perpage"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { $value['isfriend'] = 0; realname_set($value['uid'], $value['username'], $value['name'], $value['namestatus']); $fuids[] = $value['uid']; $list[$value['uid']] = $value; } } $multi = multi($count, $perpage, $page, $theurl); } else {  
$theurl = "space.\160\150\x70?uid=$space[uid]&do=$do"; $actives = array('me'=>' class="active"'); $_GET['view'] = 'me';  
$wheresql = ''; if($space['self']) { $groups = getfriendgroup(); $group = !isset($_GET['group'])?'-1':intval($_GET['group']); if($group > -1) { $wheresql = "AND \155\x61\x69\156.gid='$group'"; $theurl .= "&group=$group"; } } if($_GET['searchkey']) { $wheresql = "AND \x6d\x61i\156.fusername='$_GET[searchkey]'"; $theurl .= "&searchkey=$_GET[searchkey]"; } if($space['friendnum']) { if($wheresql) { $count = $_SGLOBAL['db']->result($_SGLOBAL['db']->query("SEL\x45\x43\124 COUNT(*) \106\x52\117\x4d ".tname('friend')." \155\141i\156 WHERE \155\x61\151n.uid='$space[uid]' AND \x6d\x61in.\163\x74\x61\164\x75s='1' $wheresql"), 0); } else { $count = $space['friendnum']; } if($count) { $query = $_SGLOBAL['db']->query("\123\x45L\105\103T s.*, f.resideprovince, f.residecity, f.note, f.spacenote, f.sex, \x6d\x61\151\x6e.gid, \x6d\141\151\156.num
				\x46\x52O\115 ".tname('friend')." \155a\x69\156
				LEFT JOIN ".tname('space')." s \x4f\x4e s.uid=\x6d\x61\151n.fuid
				LEFT JOIN ".tname('spacefield')." f ON f.uid=m\x61\151\156.fuid
				WHERE m\141\151\x6e.uid='$space[uid]' AND \155\x61i\156.s\x74a\164\x75s='1' $wheresql
				ORDER BY \x6d\x61in.num DESC, \x6d\141\x69n.dateline DESC
				LIMIT $start,$perpage"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['uid'], $value['username'], $value['name'], $value['namestatus']); $value['p'] = rawurlencode($value['resideprovince']); $value['c'] = rawurlencode($value['residecity']); $value['group'] = $groups[$value['gid']]; $value['isfriend'] = 1; $fuids[] = $value['uid']; $value['note'] = getstr($value['note'], 28, 0, 0, 0, 0, -1); $list[$value['uid']] = $value; } }  
$multi = multi($count, $perpage, $page, $theurl); $friends = array();  
$query = $_SGLOBAL['db']->query("\123E\114E\x43T f.fusername, s.name, s.namestatus, s.groupid \106\x52\x4f\115 ".tname('friend')." f
			LEFT JOIN ".tname('space')." s \117N s.uid=f.fuid
			WHERE f.uid=$_SGLOBAL[supe_uid] AND f.\163\x74\141\164u\x73='1' ORDER BY f.num DESC, f.dateline DESC LIMIT 0,100"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { $fusername = ($_SCONFIG['realname'] && $value['name'] && $value['namestatus'])?$value['name']:$value['fusername']; $friends[] = addslashes($fusername); } $friendstr = implode(',', $friends); } if($space['self']) { $groupselect = array($group => ' class="current"');  
$maxfriendnum = checkperm('maxfriendnum'); if($maxfriendnum) { $maxfriendnum = checkperm('maxfriendnum') + $space['addfriend']; } } }  
if($fuids) { $query = $_SGLOBAL['db']->query("SEL\x45C\124 * \x46\x52OM ".tname('session')." WHERE uid IN (".simplode($fuids).")"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { if(!$value['magichidden']) { $ols[$value['uid']] = $value['lastactivity']; } elseif($list[$value['uid']] && !in_array($_GET['view'], array('me', 'trace', 'blacklist'))) { unset($list[$value['uid']]); $count = $count - 1; } } } realname_get(); if(empty($_GET['view']) || $_GET['view'] == 'all') $_GET['view'] = 'me'; $a_actives = array($_GET['view'].$_GET['type'] => ' class="current"'); include_once template("space_friend");  ?>
