<?php    if(!defined('IN_UCHOME')) { exit('Access Denied'); }  
$perpage = 10; $perpage = mob_perpage($perpage); $page = empty($_GET['page'])?0:intval($_GET['page']); if($page<1) $page=1; $start = ($page-1)*$perpage;  
ckstart($start, $perpage); $dolist = array(); $count = 0; if(empty($_GET['view']) && ($space['friendnum']<$_SCONFIG['showallfriendnum'])) { $_GET['view'] = 'all'; 
}  
$f_index = ''; if($_GET['view'] == 'all') { $wheresql = "1"; $theurl = "space.p\x68\160?uid=$space[uid]&\144\157=$do&view=all"; $f_index = 'USE INDEX(dateline)'; $actives = array('all'=>' class="active"'); } else { if(empty($space['feedfriend'])) $_GET['view'] = 'me'; if($_GET['view'] == 'me') { $wheresql = "uid='$space[uid]'"; $theurl = "space.\x70\x68\160?uid=$space[uid]&\x64\157=$do&view=me"; $actives = array('me'=>' class="active"'); } else { $wheresql = "uid IN ($space[feedfriend],$space[uid])"; $theurl = "space.\160\x68\160?uid=$space[uid]&d\157=$do&view=we"; $f_index = 'USE INDEX(dateline)'; $actives = array('we'=>' class="active"'); } } $doid = empty($_GET['doid'])?0:intval($_GET['doid']); if($doid) { $count = 1; $f_index = ''; $wheresql = "doid='$doid'"; $theurl .= "&doid=$doid"; } $doids = $clist = $newdoids = array(); if(empty($count)) { $count = $_SGLOBAL['db']->result($_SGLOBAL['db']->query("S\x45\x4c\x45CT COUNT(*) F\x52O\115 ".tname('doing')." WHERE $wheresql"), 0);  
if($wheresql == "uid='$space[uid]'" && $space['doingnum'] != $count) { updatetable('space', array('doingnum' => $count), array('uid'=>$space['uid'])); } } if($count) { $query = $_SGLOBAL['db']->query("\x53\x45\x4cECT * F\122\117\x4d ".tname('doing')." $f_index
		WHERE $wheresql
		ORDER BY dateline DESC
		LIMIT $start,$perpage"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['uid'], $value['username']); $doids[] = $value['doid']; $dolist[] = $value; } }  
if($doid) { $dovalue = empty($dolist)?array():$dolist[0]; if($dovalue) { if($dovalue['uid'] == $_SGLOBAL['supe_uid']) { $actives = array('me'=>' class="active"'); } else { $space = getspace($dovalue['uid']); 
$actives = array('all'=>' class="active"'); } } }  
if($doids) { include_once(S_ROOT.'./source/class_tree.php'); $tree = new tree(); $values = array(); $query = $_SGLOBAL['db']->query("\123E\114E\x43T * F\122\117\115 ".tname('docomment')." USE \111\116\x44\105\x58(dateline) WHERE doid IN (".simplode($doids).") ORDER BY dateline"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { realname_set($value['uid'], $value['username']); $newdoids[$value['doid']] = $value['doid']; if(empty($value['upid'])) { $value['upid'] = "d\157$value[doid]"; } $tree->setNode($value['id'], $value['upid'], $value); } } foreach ($newdoids as $cdoid) { $values = $tree->getChilds("\x64\157$cdoid"); foreach ($values as $key => $id) { $one = $tree->getValue($id); $one['layer'] = $tree->getLayer($id) * 2 - 2; $one['style'] = "padding-\x6c\x65ft:{$one['layer']}em;"; if($_GET['highlight'] && $one['id'] == $_GET['highlight']) { $one['style'] .= 'color:red;font-weight:bold;'; } $clist[$cdoid][] = $one; } }  
$multi = multi($count, $perpage, $page, $theurl);  
$moodlist = array(); if($space['mood'] && empty($start)) { $query = $_SGLOBAL['db']->query("\123E\x4c\105\x43\x54 s.uid,s.username,s.name,s.namestatus,s.mood,s.updatetime,s.groupid,sf.note,sf.sex
		F\x52\x4f\115 ".tname('space')." s
		LEFT JOIN ".tname('spacefield')." sf \117\x4e sf.uid=s.uid
		WHERE s.mood='$space[mood]' ORDER BY s.updatetime DESC LIMIT 0,13"); while ($value = $_SGLOBAL['db']->fetch_array($query)) { if($value['uid'] != $space['uid']) { realname_set($value['uid'], $value['username'], $value['name'], $value['namestatus']); $moodlist[] = $value; if(count($moodlist)==12) break; } } } $upid = 0;  
realname_get(); $_TPL['css'] = 'doing'; include_once template("space_doing");  ?>
